# A simple workflow to practice github actions
name : My First WorkFlow

on:
  push:
    branches:
        - main
  workflow_dispatch:
jobs:
  my_first_job:
      name: My first job
      runs-on: ubuntu-latest
      steps:
        - name: Greet User 
          shell: bash
          run: |
                echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}'"
                echo "Current Branch is '${{ github.ref }}'"
                echo "My secret is ${{ secrets.MY_SECRET }}"
        - name: Checkout
          uses: actions/checkout@v4
        - run: tree
  Test:
      runs-on: ubuntu-latest
      # This is to apply the environment . Secrets and variables will be changed
      # according to the environment
      environment: Test
      needs: my_first_job
      steps:
        - name: Test 
          run: |
                echo "Hello ${{ vars.WHO_TO_GREET }}  from ${{ github.actor }}."
                sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
                echo "My secret is '$sec'."
  Load-Test:
      runs-on: ubuntu-latest
      environment: Load-Test
      needs: my_first_job
      steps:
        - name: Load Test
          run: |
                echo "Hello ${{ vars.WHO_TO_GREET }}  from ${{ github.actor }}."
                sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
                echo "My secret is '$sec'."
      
  Production:
      runs-on: ubuntu-latest
      environment:
        name: Production
        url: https://writeabout.net
      needs: [Test, Load-Test]
      steps:
        - name: Production 
          run: |
                echo "Hello ${{ vars.WHO_TO_GREET }}  from ${{ github.actor }}."
                sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
                echo "My secret is '$sec'."
 
                
