# A simple workflow to practice github actions
name : My First WorkFlow

on:
  push:
    branches:
        - main
    paths:
        - "doc/**"

jobs:
  my_first_job:
      name: My first job
      runs-on: ubuntu-latest
      steps:
        - name: Greet User 
          shell: bash
          run: |
                echo "Hello world from {{ github.user }}"
                echo "Current Branch is {{ github.ref }}"
        - name: Checkout
          uses: actions/checkout@v4
        - run: tree
